import {useEffect,useRef,useState} from "react";
import {FolderGit2,LoaderCircle,RefreshCw} from "lucide-react";
import {native,type GitSubmodulesState} from "@/lib/native";
import {t,useLanguage} from "@/lib/i18n";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Alert,AlertDescription} from "@/components/ui/alert";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";

export function SubmodulesManager({workspaceId,path,blocked=false,onBusyChange=()=>{},onChanged=()=>{}}:{workspaceId:string;path:string;blocked?:boolean;onBusyChange?:(busy:boolean)=>void;onChanged?:()=>void}){
  const {direction}=useLanguage();const[state,setState]=useState<GitSubmodulesState|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
  const[pending,setPending]=useState<{path:string;expectedHead:string;head:string;reviewToken:string}|null>(null);
  const generation=useRef(0);const guard=useRef(false);const identity=`${workspaceId}\0${path}`;const active=useRef(identity);active.current=identity;
  async function refresh(){const current=++generation.current;setLoading(true);try{const next=await native.submodules(workspaceId,path);if(identity===active.current&&current===generation.current)setState(next);}catch(e){if(identity===active.current&&current===generation.current)setError(String(e));}finally{if(identity===active.current&&current===generation.current)setLoading(false);}}
  useEffect(()=>{setState(null);setPending(null);setError("");setNotice("");void refresh();return()=>{generation.current++;};},[identity]);
  const locked=blocked||busy||loading||!state;
  function prepare(module:NonNullable<GitSubmodulesState["modules"]>[number]){if(locked||!state||module.blockedReason)return;setError("");setNotice("");setPending({path:module.path,expectedHead:module.expectedHead,head:module.head,reviewToken:state.reviewToken});}
  async function update(){if(!pending||locked||guard.current)return;guard.current=true;setBusy(true);onBusyChange(true);setError("");try{const message=await native.updateSubmodule(workspaceId,path,pending.path,pending.reviewToken);if(identity===active.current){setNotice(message);setPending(null);}}catch(e){if(identity===active.current){setError(String(e));setPending(null);}}finally{if(identity===active.current){await refresh();onChanged();}guard.current=false;setBusy(false);onBusyChange(false);}}
  const statusLabel=(status:string)=>t(({uninitialized:"Not initialized",ready:"At recorded commit",diverged:"Different commit",conflict:"Conflicts",blocked:"Needs attention"} as Record<string,string>)[status]||status);
  return <section className="flex flex-1 min-h-0 flex-col text-xs" data-testid="submodules-manager"><div className="flex items-center gap-2 border-b p-3"><FolderGit2 className="size-4 text-primary" /><h3 className="font-medium">{t("Submodules")}</h3><Button className="ms-auto" size="sm" variant="ghost" disabled={busy||blocked} onClick={()=>{setPending(null);setError("");void refresh();}}>{busy||loading?<LoaderCircle className="size-3.5 animate-spin" />:<RefreshCw className="size-3.5" />}{t("Refresh")}</Button></div>
    {(error||notice)&&<Alert className="m-3 w-auto" role={error?"alert":"status"} variant={error?"destructive":"default"}><AlertDescription className="whitespace-pre-wrap break-words">{t(error||notice)}</AlertDescription></Alert>}
    <div className="flex-1 overflow-auto p-4 space-y-3">{state?.warnings.map((warning,i)=><Alert key={i}><AlertDescription>{t(warning)}</AlertDescription></Alert>)}{!loading&&!state?.modules.length&&<p className="p-8 text-center text-muted-foreground">{t("No submodules configured.")}</p>}{state?.modules.map(module=><div key={`${module.name}:${module.path}`} className="border rounded-lg p-3 space-y-3"><div className="flex flex-wrap items-center gap-2"><bdi dir="ltr" className="font-medium me-auto">{module.path}</bdi><Badge variant="outline">{statusLabel(module.status)}</Badge>{module.dirty&&<Badge variant="outline" className="text-amber-600 dark:text-amber-400">{t("Local changes")}</Badge>}<Button variant="outline" size="sm" disabled={locked||!!module.blockedReason} onClick={()=>prepare(module)}>{t(module.status==="uninitialized"?"Initialize submodule":"Update submodule")}</Button></div><p dir="ltr" className="font-mono break-all text-muted-foreground">{module.url}</p><dl className="space-y-2"><div className="flex flex-wrap gap-2"><dt className="text-muted-foreground">{t("Recorded commit")}</dt><dd dir="ltr" className="font-mono break-all">{module.expectedHead}</dd></div>{module.head&&<div className="flex flex-wrap gap-2"><dt className="text-muted-foreground">{t("Checked-out commit")}</dt><dd dir="ltr" className="font-mono break-all">{module.head}</dd></div>}</dl>{module.blockedReason&&<p className="text-amber-600 dark:text-amber-400">{t(module.blockedReason)}</p>}</div>)}</div>
    {pending&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setPending(null);}}><DialogContent dir={direction} showCloseButton={!busy}><DialogHeader><DialogTitle>{t("Update submodule")}</DialogTitle><DialogDescription>{t("Initialize if needed and check out the exact commit recorded by the parent repository. This may download files. No remote branch is advanced, and no commit or push is created.")}</DialogDescription></DialogHeader><dl className="border rounded-lg p-3 space-y-3"><div><dt className="text-muted-foreground text-xs">{t("Submodule")}</dt><dd dir="ltr" className="font-mono break-all">{pending.path}</dd></div><div><dt className="text-muted-foreground text-xs">{t("Recorded commit")}</dt><dd dir="ltr" className="font-mono break-all">{pending.expectedHead}</dd></div>{pending.head&&<div><dt className="text-muted-foreground text-xs">{t("Checked-out commit")}</dt><dd dir="ltr" className="font-mono break-all">{pending.head}</dd></div>}</dl><p className="text-muted-foreground text-xs">{t("Update may take up to two minutes. Commit or stash submodule changes before updating.")}</p><p className="text-muted-foreground text-xs">{t("Before changing a checked-out commit, a recovery reference is saved inside the submodule under refs/gitorbit/recovery.")}</p><div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={()=>setPending(null)}>{t("Cancel")}</Button><Button disabled={locked} onClick={()=>void update()}>{busy&&<LoaderCircle className="size-4 animate-spin" />}{t("Update submodule")}</Button></div></DialogContent></Dialog>}
  </section>;
}
