import { useEffect, useRef, useState } from "react";
import { LoaderCircle, Plus, RefreshCw, Tag } from "lucide-react";
import { native, type GitTagState, type GitTagRequest } from "@/lib/native";
import { t, useLanguage } from "@/lib/i18n";
import { ContextActions, ActionMenuButton, type ContextAction } from "./context-actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const blank = (): GitTagRequest => ({action:"create",tag:"",revision:"HEAD",message:"",annotated:false,signed:false,remote:"",reviewToken:"",remoteTip:"",localTip:""});
export function TagManager({workspaceId, path, blocked = false, onBusyChange = () => {}, onChanged = () => {},onCreateBranch,onDeleteLocal}: {
  workspaceId: string; path: string; blocked?: boolean; onBusyChange?: (busy:boolean) => void; onChanged?: () => void;onCreateBranch?:(name:string)=>void;onDeleteLocal?:(name:string)=>void;
}) {
  const {direction}=useLanguage();const [state,setState]=useState<GitTagState|null>(null);const [remote,setRemote]=useState("");
  const [pending,setPending]=useState<GitTagRequest|null>(null);const [reviewed,setReviewed]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const guard=useRef(false);const generation=useRef(0);const identity=`${workspaceId}\0${path}`;const active=useRef(identity);active.current=identity;
  async function refresh(){const version=++generation.current;setLoading(true);try{const next=await native.tags(workspaceId,path);if(identity===active.current&&version===generation.current){setState(next);setRemote(old=>next.remotes.includes(old)?old:next.remotes[0]||"");}}catch(e){if(identity===active.current&&version===generation.current)setError(String(e));}finally{if(identity===active.current&&version===generation.current)setLoading(false);}}
  useEffect(()=>{setState(null);setPending(null);setError("");setNotice("");void refresh();return()=>{generation.current++;};},[identity]);
  const locked=blocked||busy||loading||!state;
  function create(){if(locked||!state)return;setError("");setNotice("");setReviewed(false);setPending({...blank(),reviewToken:state.reviewToken});}
  async function prepare(action:"push"|"delete-remote",tag:string){if(locked||guard.current||!remote)return;guard.current=true;setBusy(true);onBusyChange(true);setError("");setNotice("");try{const result=await native.reviewTagRemote(workspaceId,path,action,tag,remote);if(identity===active.current){setPending({...blank(),action,tag,remote,...result});setReviewed(true);}}catch(e){if(identity===active.current)setError(String(e));}finally{guard.current=false;setBusy(false);onBusyChange(false);}}
  async function execute(){if(!pending||!reviewed||locked||guard.current)return;guard.current=true;setBusy(true);onBusyChange(true);setError("");try{const message=await native.tagAction(workspaceId,path,pending);if(identity===active.current){setNotice(message);setPending(null);}}catch(e){if(identity===active.current){setError(String(e));setPending(null);}}finally{if(identity===active.current){await refresh();onChanged();}guard.current=false;setBusy(false);onBusyChange(false);}}
  function tagActions(name:string):ContextAction[]{return [
    {label:t("Push tag"),run:()=>void prepare("push",name),disabled:locked||!remote},
    ...(onCreateBranch?[{label:t("Create branch"),run:()=>onCreateBranch(name),disabled:locked}]:[]),
    ...(onDeleteLocal?[{label:t("Delete tag"),run:()=>onDeleteLocal(name),disabled:locked,destructive:true,separator:true}]:[]),
    {label:t("Delete remote tag"),run:()=>void prepare("delete-remote",name),disabled:locked||!remote,destructive:true},
  ];}
  const label=t(pending?.action==="push"?"Push tag":pending?.action==="delete-remote"?"Delete remote tag":"Create tag");
  return <section className="flex flex-1 min-h-0 flex-col text-xs" data-testid="tag-manager"><div className="flex items-center flex-wrap gap-2 border-b p-3"><Tag className="size-4 text-primary" /><span className="font-medium">{t("Tags")}</span><Select value={remote} disabled={locked||!state?.remotes.length} onValueChange={setRemote}><SelectTrigger aria-label={t("Tag remote")} className="w-36 h-8 ms-auto"><SelectValue placeholder={t("Remote")} /></SelectTrigger><SelectContent>{state?.remotes.map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select><Button size="sm" variant="outline" disabled={locked} onClick={create}><Plus className="size-3.5" />{t("Create tag")}</Button><Button size="sm" variant="ghost" disabled={blocked||busy} onClick={()=>{setPending(null);setError("");void refresh();}}>{loading||busy?<LoaderCircle className="size-3.5 animate-spin" />:<RefreshCw className="size-3.5" />}{t("Refresh")}</Button></div>
    {(error||notice)&&<Alert className="m-3 w-auto" role={error?"alert":"status"} variant={error?"destructive":"default"}><AlertDescription className="whitespace-pre-wrap break-words">{t(error||notice)}</AlertDescription></Alert>}
    <div className="flex-1 overflow-auto p-4 space-y-3">{!loading&&!state?.tags.length&&<p className="p-8 text-center text-muted-foreground">{t("No tags yet.")}</p>}{state?.tags.map(tag=><ContextActions key={tag.name} label={tag.name} actions={tagActions(tag.name)}><div className="border rounded-lg p-3 space-y-2"><div className="flex flex-wrap items-center gap-2"><bdi dir="ltr" className="font-medium me-auto">{tag.name}</bdi><span className="text-muted-foreground">{t(tag.annotated?"Annotated tag":"Lightweight tag")}</span><Button size="sm" variant="outline" disabled={locked||!remote} onClick={()=>void prepare("push",tag.name)}>{t("Push tag")}</Button><ActionMenuButton label={tag.name} disabled={locked} actions={tagActions(tag.name).slice(1)}/></div><p dir="ltr" className="font-mono text-muted-foreground break-all">{tag.commitId}</p>{tag.subject&&<p dir="auto" className="break-words">{tag.subject}</p>}</div></ContextActions>)}</div>
    {pending&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setPending(null);}}><DialogContent dir={direction} showCloseButton={!busy} className="sm:max-w-xl"><DialogHeader><DialogTitle>{label}</DialogTitle><DialogDescription>{t(pending.action==="delete-remote"?"Delete the reviewed tag from the selected server. The local tag is preserved. This affects collaborators.":pending.action==="push"?"Push this tag only. Existing remote tags are never replaced.":"Create a lightweight, annotated, or signed local tag at a commit.")}</DialogDescription></DialogHeader>
      {pending.action==="create"&&!reviewed?<div className="space-y-4"><div className="space-y-2"><label htmlFor="tag-name">{t("Tag name")}</label><Input id="tag-name" dir="ltr" value={pending.tag} autoFocus maxLength={255} onChange={e=>setPending({...pending,tag:e.target.value})} /></div><div className="space-y-2"><label htmlFor="tag-revision">{t("Commit or revision")}</label><Input id="tag-revision" dir="ltr" value={pending.revision} maxLength={512} onChange={e=>setPending({...pending,revision:e.target.value})} /></div><label className="flex items-center gap-2"><Checkbox checked={pending.annotated} disabled={pending.signed} onCheckedChange={value=>setPending({...pending,annotated:value===true})} />{t("Annotated tag")}</label><label className="flex items-center gap-2"><Checkbox checked={pending.signed} onCheckedChange={value=>setPending({...pending,signed:value===true,annotated:value===true||pending.annotated})} />{t("Sign tag using configured key")}</label>{(pending.annotated||pending.signed)&&<div className="space-y-2"><label htmlFor="tag-annotation">{t("Annotation message")}</label><Textarea id="tag-annotation" dir="auto" value={pending.message} maxLength={65536} onChange={e=>setPending({...pending,message:e.target.value})} /></div>}<div className="flex gap-2 justify-end"><Button variant="outline" onClick={()=>setPending(null)}>{t("Cancel")}</Button><Button disabled={!pending.tag.trim()||!pending.revision.trim()||(pending.annotated||pending.signed)&&!pending.message.trim()} onClick={()=>setReviewed(true)}>{t("Review tag")}</Button></div></div>:<><dl className="space-y-3 border rounded-lg p-3"><div><dt className="text-muted-foreground">{t("Tag name")}</dt><dd dir="ltr" className="font-mono break-all">{pending.tag}</dd></div>{pending.action==="create"?<><div><dt className="text-muted-foreground">{t("Commit or revision")}</dt><dd dir="ltr" className="font-mono">{pending.revision}</dd></div><p>{t(pending.signed?"Signed tag":pending.annotated?"Annotated tag":"Lightweight tag")}</p>{pending.message&&<p dir="auto" className="whitespace-pre-wrap break-words">{pending.message}</p>}</>:<><div><dt className="text-muted-foreground">{t("Remote")}</dt><dd dir="ltr">{pending.remote}</dd></div><div><dt className="text-muted-foreground">{t("Reviewed remote tag")}</dt><dd dir="ltr" className="font-mono break-all">{pending.remoteTip||t("Does not exist")}</dd></div><div><dt className="text-muted-foreground">{t("Local tag object")}</dt><dd dir="ltr" className="font-mono break-all">{pending.localTip}</dd></div></>}</dl><div className="flex gap-2 justify-end"><Button variant="outline" disabled={busy} onClick={()=>pending.action==="create"?setReviewed(false):setPending(null)}>{t(pending.action==="create"?"Back":"Cancel")}</Button><Button variant={pending.action==="delete-remote"?"destructive":"default"} disabled={locked} onClick={()=>void execute()}>{busy&&<LoaderCircle className="size-4 animate-spin" />}{label}</Button></div></>}
    </DialogContent></Dialog>}
  </section>;
}
